// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sblslqjyihiwbphnqoli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNibHNscWp5aWhpd2JwaG5xb2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0ODI0MzIsImV4cCI6MjA2MjA1ODQzMn0.zLWMDRgj_LsKZ3CXDq4EhoLWUvXxp4gsobRi0PU75uE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);